
    create table categorie (
       code integer generated by default as identity,
        description varchar(255),
        libelle varchar(255),
        primary key (code)
    )

    create table client (
       code varchar(5) not null,
        adresse varchar(60),
        code_postal varchar(10),
        pays varchar(15),
        region varchar(15),
        ville varchar(15),
        contact varchar(30),
        fax varchar(24),
        fonction varchar(30),
        societe varchar(40) not null,
        telephone varchar(24),
        primary key (code)
    )

    create table commande (
       numero integer generated by default as identity,
        adresse varchar(60),
        code_postal varchar(10),
        pays varchar(15),
        region varchar(15),
        ville varchar(15),
        destinataire varchar(40),
        envoyeele date,
        port decimal(18,2),
        remise decimal(10,2) not null,
        saisiele date not null,
        client_code varchar(5) not null,
        primary key (numero)
    )

    create table ligne (
       id integer generated by default as identity,
        quantite smallint not null,
        commande_numero integer not null,
        produit_reference integer not null,
        primary key (id)
    )

    create table produit (
       reference integer generated by default as identity,
        fournisseur integer not null,
        indisponible smallint not null,
        niveau_de_reappro smallint not null,
        nom varchar(255),
        prix_unitaire decimal(19,2),
        quantite_par_unite varchar(255),
        unites_commandees smallint not null,
        unites_en_stock smallint not null,
        categorie_code integer not null,
        primary key (reference)
    )

    alter table categorie 
       add constraint UK_201klrwuww0os41kte46ac6lq unique (libelle)

    alter table ligne 
       add constraint UK6smofc97ttqyewkptp7jx7sen unique (commande_numero, produit_reference)

    alter table produit 
       add constraint UK_p3flguk26lkj16433geia6xx8 unique (nom)

    alter table commande 
       add constraint FK29k1npc26p1jolstkfgmoinnf 
       foreign key (client_code) 
       references client

    alter table ligne 
       add constraint FK6jxlgqievklsvlub5jdc6uh80 
       foreign key (commande_numero) 
       references commande

    alter table ligne 
       add constraint FK1akvplemdmbafp7pumwso9exi 
       foreign key (produit_reference) 
       references produit

    alter table produit 
       add constraint FK7u85qda7i65v0v9u7j3r6xmlk 
       foreign key (categorie_code) 
       references categorie
